[connections.gsheets]
inventory_url = "https://docs.google.com/spreadsheets/d/1e-CY4ucnuyWhH5A8mjBOrDWyPitcHyo8baN-bJqIcjo/edit?usp=drive_web"
logs_url = "https://docs.google.com/spreadsheets/d/1q5WNxSWU0qvLM6cpgL6V20E_W0t5a7_qRt0yv8k_-PM/edit?usp=drive_web"
